### ISSUE TITLE
python

### ISSUE THREAD

**Issue by 0x62797465** [CattopyTheWeb/fake-update-prank#1]
issue: it's python

**Comment by CattopyTheWeb** [comment]
Can you give me a bit more context?

**Comment by CattopyTheWeb** [comment]
What does the error say?

**Comment by CattopyTheWeb** [comment]
@Boberttt I have compiled a exe file for Windows

**Comment by 0x62797465** [comment]
no error, it's python

**Comment by CattopyTheWeb** [comment]
I have compiled a exe file for Windows

**Comment by 0x62797465** [comment]
what did you use for compiling?

**Comment by CattopyTheWeb** [comment]
pyautogui

**Comment by 0x62797465** [comment]
that still runs python code, use nukitia (like a non barbain) so it gets turned to c before compiling

**Comment by CattopyTheWeb** [comment]
well it works and that's all I care about. I might use nukitia to recompile the new code

**Comment by 0x62797465** [comment]
as long as it's still python, this remains an issue

**Comment by CattopyTheWeb** [comment]
Python wasn't made to run without the translator but people found a way. Anyway, the compiled exe file should work.

**Comment by 0x62797465** [comment]
but it's python, please change this to c/scratch/golang/assembly/anything but python

**Comment by CattopyTheWeb** [comment]
I can only code in python.
